### PR TITLE
Fix Null class for PHP 7

### PR DESCRIPTION
**Pull request by Josh-Bruce**

### CODE REVIEW

**Comment by Josh-Bruce** [comment]
This is a PR for issue https://github.com/romanpitak/dotMailer-API-v2-PHP-client/issues/22 need it for a project 👍

**Comment by DavidDowdall** [comment]
I have just had to make the same change on a project and I would guess moving forward this will be required more and more, this would be a good PR to merge in.

Great library though, thank you.

**Comment by rgrebenchuk** [comment]
Is there any plan to merge PR?

**Comment by fbenas** [comment]
I'm also in need of this merge. Anyone here think there's a chance of that? or perhaps people moved on to other packages?

**Comment by Josh-Bruce** [comment]
@fbenas Have been waiting for this for nearly a year. Just ended up pointing the composer dependancy to my fork with the fix :)

**Comment by ngse** [comment]
Assume this project is dead and the maintainer is no longer active, just encountered this issue and it's been nearly 2 years since this PR was opened. Shame!

**Pull request closed without merging**
