### PR TITLE
Minor formating fix

### PR DESCRIPTION
**Pull request by Zifius**

### CODE REVIEW

**Comment by romanpitak** [comment]
Thanks :)

**Comment by Zifius** [comment]
@romanpitak thanks for the quick merge :) I missed another small spot, sorry for that

P.S. This is just small eye-bugging changes. I need to implement ApiProgramEnrolment wrapper. Will this be accepted?

**Comment by romanpitak** [comment]
Truth be told, I don't know what exactly an `ApiProgramEnrolment wrapper` is, so I don't know if I'll be accepting it. Feel free to tell me more. 

Anyway - a wrapper (as I understand it) should have its separate repository and only include the library it's wrapping (like the [Laravel wrapper](https://github.com/industrious-mouse/laravel-dotmailer) of my lib.). (Feel free to prove me wrong.)

**Comment by Zifius** [comment]
Sorry I wasn't clear. I meant I need to implement the API calls related to http://api.dotmailer.com/v2/help/wadl#ProgramsEnrolments

**Comment by romanpitak** [comment]
Oh yes! I wasn't aware of being out of date. It seems they added it into the API after I have implemented it. Please do implement it and I will gladly accept :)

Notes:
- Please test it. I currently don't have access to any working dotMailer accounts. 
- Please adhere to the code standards. I'm trying to maintain a readable code and good grades on [code climate](https://www.codacy.com/public/roman/dotMailer-API-v2-PHP-client/dashboard) and [codacy](https://codeclimate.com/github/romanpitak/dotMailer-API-v2-PHP-client)

**Comment by Zifius** [comment]
Absolutely, I'll adhere the coding standards and we are testing the POST implementation right now :) Will keep you posted as there are several GETs to implement as well

**Comment by romanpitak** [comment]
I had a look at your code just now. Apart from some `missing lines at the end of file` it looks good. Please feel free to add your own headers to the files you create.

**Comment by bsstaveley** [comment]
@romanpitak @Zifius Happy to hook either/both of you guys with accounts to use for testing etc, just give me a shout

**Comment by romanpitak** [comment]
@bsstaveley Thanks! I'd love to be able to test the code again :) Please send me more info on roman@pitak.net

**Pull request merged**
